### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Review my app

### ISSUE THREAD

**Issue by vgudla** [vgudla/TodoApp#1] opened 2015-09-25 11:30 UTC
@codepathreview @codepath

**Comment by nidhi1608** [comment] 2015-09-27 20:07
Vinesh,

Looks great! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.
Nice job with the project, hope you found it as a helpful introduction.

We are reviewing the submissions right now and will get in touch with you via email a few days after the submission closing date, October 2nd, 2015. In the mean time, you may consider working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and let us know if you have any questions.

**Comment by vgudla** [comment] 2015-09-30 07:15
Thank you Nidhi. Just an update. I added the following features to the app. 
Will try to improve it once I get some time :)

* Persist the todo items [into SQLite](http://guides.codepath.com/android/Persisting-Data-to-the-
* Improve style of the todo items in the list [using a custom adapter]
* Add support for completion due dates for todo items (and display within listview item)
* Add support for selecting the priority of each todo item (and display in listview item)

Walkthrough here - http://s27.postimg.org/dbkot3iwz/Todo_Demo.gif

**Comment by nidhi1608** [comment] 2015-09-30 19:40
Nice, glad you got a chance to work on most of the extensions.

**Closed** 2015-11-02 18:14 UTC
